// Package models holds the plain data structs that mirror the database
// schema. No behavior lives here, that's in internal/auth and internal/session.
package models

import (
	"database/sql"
	"time"
)

// User mirrors the `users` table. TOTPSecret and LockedUntil use sql.Null*
// types since those columns are nullable.
type User struct {
	ID             string         `db:"id"` // UUID text, generated by Postgres via gen_random_uuid()
	Username       string         `db:"username"`
	PasswordHash   string         `db:"password_hash"`
	TOTPSecret     sql.NullString `db:"totp_secret"`
	TOTPEnabled    bool           `db:"totp_enabled"`
	FailedAttempts int            `db:"failed_attempts"`
	LockedUntil    sql.NullTime   `db:"locked_until"`
	CreatedAt      time.Time      `db:"created_at"`
	LastLoginAt    sql.NullTime   `db:"last_login_at"`
}

// Session mirrors the `sessions` table (migrations/0001_init.up.sql).
type Session struct {
	Token     string    `db:"token"`   // PK; opaque random session token
	UserID    string    `db:"user_id"` // FK -> users.id
	CreatedAt time.Time `db:"created_at"`
	ExpiresAt time.Time `db:"expires_at"`
}
